grails-app/domain/br/edu/unirn/tickit/dominio/Chamado.groovy
package br.edu.unirn.tickit.dominio
import br.edu.unirn.sisuni.utils.CalendarUtils
import br.edu.unirn.tickit.acesso.Usuario
/**
 * Classe responsável por Armazenar informações sobre o Chamado.
 * @author: Jefferson Silva
 */
class Chamado {

    String titulo
    String descricao
    String emailSolicitante
    boolean ativo = Boolean.TRUE
    Usuario usuarioCadastrante
    Setor setorSolicitante
    AreaAtendimento areaAtendimento
    Date dateCreated

    @Override
    String toString() {
        titulo
    }

    static constraints = {
        titulo blank:false
        descricao blank:false
        emailSolicitante blank:false, nullable:false,email:true
        setorSolicitante nullable:false
        areaAtendimento nullable: false
        usuarioCadastrante nullable:true
        ativo(attributes:[showInForm:false])
        dateCreated(attributes:[fieldName: "Data de Cadastro"])
    }

    static mapping = {
        dateCreated column: "data_de_cadastro"
        descricao type: "text"
    }

    static searchFields = ["titulo","emailSolicitante"]

    public String getDateCreatedAsString(){
        return CalendarUtils.getStriWithTimengByDate(this.dateCreated)
    }

}

grails-app/controllers/br/edu/unirn/tickit/dominio/ChamadoController.groovy
package br.edu.unirn.tickit.dominio


import br.edu.unirn.tickit.acesso.Usuario
import br.edu.unirn.tickit.acesso.Perfil
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import java.util.regex.Pattern
import java.util.regex.Matcher
import java.text.SimpleDateFormat

@Transactional(readOnly = true)
class ChamadoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Chamado.list(params), model:[chamadoInstanceCount: Chamado.count()]
    }

    @Transactional
    def show(Chamado chamadoInstance) {




         /**
        *Condiçao onde um comentário é adicionado do chamado
        */
        if(params.comentario != null && !params.comentario.trim().equals("")){

            ComentarioChamado cc = new ComentarioChamado()

            cc.comentario = params.comentario
            cc.usuarioCadastrante = session.usuario
            cc.chamado = Chamado.get(chamadoInstance.id)
            cc.save flush:true

            render(view:"show", model:[chamadoInstance:chamadoInstance, areasAtendimento:AreaAtendimento.findAllWhere(ativo:true),
                    responsaveis:Usuario.findAllWhere(ativo:true),
                    equipamentos:Equipamento.findAllWhere(ativo:true),
                    statusChamado:Status.findAllWhere(ativo:true),
                    historicoStatus:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado ORDER BY sc.dateCreated DESC", [chamado:chamadoInstance]),
                    status:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado and sc.ativo = true ", [chamado:chamadoInstance]),
                    equipamentosChamado:EquipamentoChamado.executeQuery("select ec from EquipamentoChamado ec where ec.chamado = :chamado and ec.ativo = true ORDER BY ec.dateCreated DESC", [chamado:chamadoInstance]),
                    comentariosChamado:ComentarioChamado.executeQuery("select cc from ComentarioChamado cc where cc.chamado = :chamado and cc.ativo = true ORDER BY cc.dateCreated ASC", [chamado:chamadoInstance]),
                    responsaveisChamado:UsuarioChamado.executeQuery("select uc from UsuarioChamado uc where uc.chamado = :chamado and uc.ativo = true ORDER BY uc.dateCreated DESC", [chamado:chamadoInstance]),
                    anexosDoChamado:AnexoChamado.executeQuery("select ac from AnexoChamado ac where ac.chamado = :chamado and ac.ativo = true ", [chamado:chamadoInstance]),
                    mensagemSucesso:"Comentário adicionado com sucesso."])
                    return

        }



        /**
        *Condiçao onde um responsável é removido do chamado
        */
        if(params.usuarioId != null){


            if(session?.usuario?.hasPerfil(Perfil.findByNome("Padrão"))){
                UsuarioChamado uc = new UsuarioChamado();
                if(!uc.isUsuarioChamado(chamadoInstance, session?.usuario)){
                     render(view:"show", model:[chamadoInstance:chamadoInstance, areasAtendimento:AreaAtendimento.findAllWhere(ativo:true),
                    responsaveis:Usuario.findAllWhere(ativo:true),
                    equipamentos:Equipamento.findAllWhere(ativo:true),
                    statusChamado:Status.findAllWhere(ativo:true),
                    historicoStatus:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado ORDER BY sc.dateCreated DESC", [chamado:chamadoInstance]),
                    status:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado and sc.ativo = true ", [chamado:chamadoInstance]),
                    equipamentosChamado:EquipamentoChamado.executeQuery("select ec from EquipamentoChamado ec where ec.chamado = :chamado and ec.ativo = true ORDER BY ec.dateCreated DESC", [chamado:chamadoInstance]),
                    comentariosChamado:ComentarioChamado.executeQuery("select cc from ComentarioChamado cc where cc.chamado = :chamado and cc.ativo = true ORDER BY cc.dateCreated ASC", [chamado:chamadoInstance]),
                    responsaveisChamado:UsuarioChamado.executeQuery("select uc from UsuarioChamado uc where uc.chamado = :chamado and uc.ativo = true ORDER BY uc.dateCreated DESC", [chamado:chamadoInstance]),
                    anexosDoChamado:AnexoChamado.executeQuery("select ac from AnexoChamado ac where ac.chamado = :chamado and ac.ativo = true ", [chamado:chamadoInstance]),
                    mensagemErro:"Apenas responsaveis pelo chamado poderão remover responsaveis do chamado."])
                    return
                }
            }


            UsuarioChamado us = UsuarioChamado.get(params.long('usuarioId'))

            us.ativo = false

            us.save flush:true

            render(view:"show", model:[chamadoInstance:chamadoInstance, areasAtendimento:AreaAtendimento.findAllWhere(ativo:true),
                    responsaveis:Usuario.findAllWhere(ativo:true),
                    equipamentos:Equipamento.findAllWhere(ativo:true),
                    statusChamado:Status.findAllWhere(ativo:true),
                    historicoStatus:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado ORDER BY sc.dateCreated DESC", [chamado:chamadoInstance]),
                    status:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado and sc.ativo = true ", [chamado:chamadoInstance]),
                    equipamentosChamado:EquipamentoChamado.executeQuery("select ec from EquipamentoChamado ec where ec.chamado = :chamado and ec.ativo = true ORDER BY ec.dateCreated DESC", [chamado:chamadoInstance]),
                    comentariosChamado:ComentarioChamado.executeQuery("select cc from ComentarioChamado cc where cc.chamado = :chamado and cc.ativo = true ORDER BY cc.dateCreated ASC", [chamado:chamadoInstance]),
                    responsaveisChamado:UsuarioChamado.executeQuery("select uc from UsuarioChamado uc where uc.chamado = :chamado and uc.ativo = true ORDER BY uc.dateCreated DESC", [chamado:chamadoInstance]),
                    anexosDoChamado:AnexoChamado.executeQuery("select ac from AnexoChamado ac where ac.chamado = :chamado and ac.ativo = true ", [chamado:chamadoInstance]),
                    mensagemSucesso:"Responsável removido com sucesso."])
                    return

        }

         /**
        *Condiçao onde um responsável é adicionado ao chamado
        */
        if(params.addResponsavel != null){

            if(session?.usuario?.hasPerfil(Perfil.findByNome("Padrão"))){
                UsuarioChamado uc = new UsuarioChamado();
                if(!uc.isUsuarioChamado(chamadoInstance, session?.usuario)){
                     render(view:"show", model:[chamadoInstance:chamadoInstance, areasAtendimento:AreaAtendimento.findAllWhere(ativo:true),
                    responsaveis:Usuario.findAllWhere(ativo:true),
                    equipamentos:Equipamento.findAllWhere(ativo:true),
                    statusChamado:Status.findAllWhere(ativo:true),
                    historicoStatus:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado ORDER BY sc.dateCreated DESC", [chamado:chamadoInstance]),
                    status:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado and sc.ativo = true ", [chamado:chamadoInstance]),
                    equipamentosChamado:EquipamentoChamado.executeQuery("select ec from EquipamentoChamado ec where ec.chamado = :chamado and ec.ativo = true ORDER BY ec.dateCreated DESC", [chamado:chamadoInstance]),
                    comentariosChamado:ComentarioChamado.executeQuery("select cc from ComentarioChamado cc where cc.chamado = :chamado and cc.ativo = true ORDER BY cc.dateCreated ASC", [chamado:chamadoInstance]),
                    responsaveisChamado:UsuarioChamado.executeQuery("select uc from UsuarioChamado uc where uc.chamado = :chamado and uc.ativo = true ORDER BY uc.dateCreated DESC", [chamado:chamadoInstance]),
                    anexosDoChamado:AnexoChamado.executeQuery("select ac from AnexoChamado ac where ac.chamado = :chamado and ac.ativo = true ", [chamado:chamadoInstance]),
                    mensagemErro:"Apenas responsaveis pelo chamado poderão adicionar responsável ao chamado."])
                    return
                }
            }


            def responsavelDoChamado = UsuarioChamado.executeQuery("select us from UsuarioChamado us where us.chamado = :chamado and us.usuario = :usuario and us.ativo = true", [chamado:chamadoInstance, usuario:Usuario.get(params.long('addResponsavel'))])

             /**
            *Verifica se um responsável já está vinculado ao chamado
            */
            if(!responsavelDoChamado.isEmpty()){


                render(view:"show", model:[chamadoInstance:chamadoInstance, areasAtendimento:AreaAtendimento.findAllWhere(ativo:true),
                responsaveis:Usuario.findAllWhere(ativo:true),
                equipamentos:Equipamento.findAllWhere(ativo:true),
                statusChamado:Status.findAllWhere(ativo:true),
                historicoStatus:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado ORDER BY sc.dateCreated DESC", [chamado:chamadoInstance]),
                status:StatusChamado.executeQuery("select sc from StatusChamado sc where sc.chamado = :chamado and sc.ativo = true ", [chamado:chamadoInstance]),
                equipamentosChamado:EquipamentoChamado.executeQuery("select ec from EquipamentoChamado ec where ec.chamado = :chamado and ec.ativo = true ORDER BY ec.dateCreated DESC", [chamado:chamadoInstance]),
                comentariosChamado:ComentarioChamado.executeQuery("select cc from ComentarioChamado cc where cc.chamado = :chamado and cc.ativo = true ORDER BY cc.dateCreated ASC", [chamado:chamadoInstance]),

grails-app/views/chamado/_form.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Chamado" %>



<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'titulo', 'error')} required">
	<label for="titulo">
		<g:message code="chamado.titulo.label" default="Titulo" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="titulo" required="" value="${chamadoInstance?.titulo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'descricao', 'error')} required">
	<label for="descricao">
		<g:message code="chamado.descricao.label" default="Descricao" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="descricao" required="" value="${chamadoInstance?.descricao}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'emailSolicitante', 'error')} required">
	<label for="emailSolicitante">
		<g:message code="chamado.emailSolicitante.label" default="Email Solicitante" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="emailSolicitante" required="" value="${chamadoInstance?.emailSolicitante}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'setorSolicitante', 'error')} required">
	<label for="setorSolicitante">
		<g:message code="chamado.setorSolicitante.label" default="Setor Solicitante" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="setorSolicitante" name="setorSolicitante.id" from="${br.edu.unirn.tickit.dominio.Setor.list()}" optionKey="id" required="" value="${chamadoInstance?.setorSolicitante?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'areaAtendimento', 'error')} required">
	<label for="areaAtendimento">
		<g:message code="chamado.areaAtendimento.label" default="Area Atendimento" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="areaAtendimento" name="areaAtendimento.id" from="${br.edu.unirn.tickit.dominio.AreaAtendimento.list()}" optionKey="id" required="" value="${chamadoInstance?.areaAtendimento?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'usuarioCadastrante', 'error')} ">
	<label for="usuarioCadastrante">
		<g:message code="chamado.usuarioCadastrante.label" default="Usuario Cadastrante" />
		
	</label>
	<g:select id="usuarioCadastrante" name="usuarioCadastrante.id" from="${br.edu.unirn.tickit.acesso.Usuario.list()}" optionKey="id" value="${chamadoInstance?.usuarioCadastrante?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: chamadoInstance, field: 'ativo', 'error')} ">
	<label for="ativo">
		<g:message code="chamado.ativo.label" default="Ativo" />
		
	</label>
	<g:checkBox name="ativo" showInForm="false" value="${chamadoInstance?.ativo}" />

</div>

grails-app/views/chamado/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chamado.label', default: 'Chamado')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-chamado" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-chamado" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${chamadoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${chamadoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:chamadoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/chamado/edit.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Chamado" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chamado.label', default: 'Chamado')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-chamado" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-chamado" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${chamadoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${chamadoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:chamadoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${chamadoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/chamado/index.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Chamado" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'chamado.label', default: 'Chamado')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-chamado" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-chamado" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="titulo" title="${message(code: 'chamado.titulo.label', default: 'Titulo')}" />
					
						<g:sortableColumn property="descricao" title="${message(code: 'chamado.descricao.label', default: 'Descricao')}" />
					
						<g:sortableColumn property="emailSolicitante" title="${message(code: 'chamado.emailSolicitante.label', default: 'Email Solicitante')}" />
					
						<th><g:message code="chamado.setorSolicitante.label" default="Setor Solicitante" /></th>
					
						<th><g:message code="chamado.areaAtendimento.label" default="Area Atendimento" /></th>
					
						<th><g:message code="chamado.usuarioCadastrante.label" default="Usuario Cadastrante" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${chamadoInstanceList}" status="i" var="chamadoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${chamadoInstance.id}">${fieldValue(bean: chamadoInstance, field: "titulo")}</g:link></td>
					
						<td>${fieldValue(bean: chamadoInstance, field: "descricao")}</td>
					
						<td>${fieldValue(bean: chamadoInstance, field: "emailSolicitante")}</td>
					
						<td>${fieldValue(bean: chamadoInstance, field: "setorSolicitante")}</td>
					
						<td>${fieldValue(bean: chamadoInstance, field: "areaAtendimento")}</td>
					
						<td>${fieldValue(bean: chamadoInstance, field: "usuarioCadastrante")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${chamadoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>