grails-app/domain/br/edu/unirn/tickit/dominio/AreaAtendimento.groovy
package br.edu.unirn.tickit.dominio

import br.edu.unirn.tickit.acesso.Usuario
/**
 * Por ser uma aplicação genérica possa ser que em outros locais um setor tenham mais
 * de uma Área de Atendimento.
 * Por exemplo: Setor manutenção que tem a Área eletríca, Área Hidráulica.
 * @author: Jefferson Silva
 */
class AreaAtendimento {

    String nome
    String email
    boolean ativo = Boolean.TRUE
    Usuario usuarioCadastrante
    Date dateCreated

    @Override
    String toString() {
        nome
    }

    static constraints = {
        nome blank:false,unique:true
        email blank:false,email:true,nullable:false
        ativo(attributes:[showInForm:false])
        dateCreated(attributes:[fieldName: "Data de Cadastro"])
    }

    static mapping = {
        dateCreated column: "data_de_cadastro"
    }

    static searchFields = ["nome"]
}

grails-app/domain/br/edu/unirn/tickit/dominio/Equipamento.groovy
package br.edu.unirn.tickit.dominio

import br.edu.unirn.tickit.acesso.Usuario
/**
 * Classe responsável por Armazenar informações sobre o Equipamento
 * @author: Jefferson Silva
 */
class Equipamento {

    String nome
    Date dataCompra
    boolean locado = Boolean.FALSE
    String observacoes
    String tombamento
    boolean ativo = Boolean.TRUE
    TipoEquipamento tipoEquipamento
    Usuario usuarioCadastrante
    Date dateCreated

    @Override
    String toString() {
        nome
    }

    static constraints = {
        nome blank:false
        tipoEquipamento()
        dataCompra(attributes:[fieldName: "Data de Compra"])
        locado()
        observacoes nullable: true
        ativo(attributes:[showInForm:false])
        tombamento nullable: true
        tombamento validator: {val,obj ->
            if(obj?.locado && val == null)
                return["br.edu.unirn.tickit.dominio.Equipamento.tombamento.default.invalid.validator.message"]
        }
        dateCreated(attributes:[fieldName: "Data de Cadastro"])

    }

    static mapping = {
        dateCreated column: "data_de_cadastro"
        observacoes type: "text"
    }

    static searchFields = ["nome,tombamento"]
}

grails-app/controllers/br/edu/unirn/tickit/dominio/AreaAtendimentoController.groovy
package br.edu.unirn.tickit.dominio


import org.codehaus.groovy.grails.commons.GrailsClassUtils
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AreaAtendimentoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AreaAtendimento.list(params), model:[areaAtendimentoInstanceCount: AreaAtendimento.count()]
    }

    def show(AreaAtendimento areaAtendimentoInstance) {
        respond areaAtendimentoInstance
    }

    def create() {
        respond new AreaAtendimento(params)
    }

    @Transactional
    def save(AreaAtendimento areaAtendimentoInstance) {
         withForm {
            if (areaAtendimentoInstance == null) {
                notFound()
                return
            }


            areaAtendimentoInstance.usuarioCadastrante = session?.usuario
            areaAtendimentoInstance.email = params?.email
            areaAtendimentoInstance.clearErrors()
            areaAtendimentoInstance.save (flush:true)


             if (areaAtendimentoInstance.hasErrors()) {
                respond areaAtendimentoInstance.errors, view:'create'
                return
            }

            areaAtendimentoInstance.save flush:true

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.created.message', args: [message(code: 'areaAtendimento.label', default: 'Área de Atendimento'), areaAtendimentoInstance], encodeAs: "None")
                    redirect action: "index", method: "GET"
                }
                '*' { respond areaAtendimentoInstance, [status: CREATED] }
            }
        }.invalidToken {
            flash.message = "Requisição inválida. Por favor, tente reiniciar a operação"
            redirect action: 'index'
        }
    }

    def edit(AreaAtendimento areaAtendimentoInstance) {
        respond areaAtendimentoInstance
    }

    @Transactional
    def update(AreaAtendimento areaAtendimentoInstance) {
        if (areaAtendimentoInstance == null) {
            notFound()
            return
        }

        if (areaAtendimentoInstance.hasErrors()) {
            respond areaAtendimentoInstance.errors, view:'edit'
            return
        }

        areaAtendimentoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'AreaAtendimento.label', default: 'AreaAtendimento'), areaAtendimentoInstance.id])
                redirect areaAtendimentoInstance
            }
            '*'{ respond areaAtendimentoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(AreaAtendimento areaAtendimentoInstance) {

        if (areaAtendimentoInstance == null) {
            notFound()
            return
        }

        areaAtendimentoInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'AreaAtendimento.label', default: 'AreaAtendimento'), areaAtendimentoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'areaAtendimento.label', default: 'AreaAtendimento'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/areaAtendimento/_form.gsp
<%@ page import="br.edu.unirn.tickit.dominio.AreaAtendimento" %>


<div class="form-group ${hasErrors(bean: areaAtendimentoInstance, field: 'nome', 'error')} required">
	<label for="nome" class="col-sm-2 control-label">
		<g:message code="areaAtendimento.nome.label" default="Nome" />:
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-5">
		<g:textField name="nome" required="" maxlength="255" value="${areaAtendimentoInstance?.nome}"/>

		<g:hasErrors bean="${areaAtendimentoInstance}" field="nome">
			<span class="help-block error"><g:renderErrors bean="${areaAtendimentoInstance}" field="nome" as="list" /></span>
		</g:hasErrors>
	</div>
</div>

<div class="form-group ${hasErrors(bean: areaAtendimentoInstance, field: 'email', 'error')} required">
	<label for="email" class="col-sm-2 control-label">
		<g:message code="areaAtendimento.email.label" default="Email" />:
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-5">
		<g:textField name="email" required="" maxlength="255" value="${areaAtendimentoInstance?.email}"/>

		<g:hasErrors bean="${areaAtendimentoInstance}" field="email">
			<span class="help-block error"><g:renderErrors bean="${areaAtendimentoInstance}" field="email" as="list" /></span>
		</g:hasErrors>
	</div>
</div>

grails-app/views/areaAtendimento/create.gsp
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'areaAtendimento.label', default: 'Área de Atendimento')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<!-- Content Header (Page header) -->
<section class="content-header">
	<ol class="breadcrumb">
		<li><g:link class="list" action="index">Listagem</g:link></li>
		<li class="active"><g:message code="default.new.label" args="[entityName]" /></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<!-- Default box -->
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.create.label" args="[entityName]" /></h3>
		</div>
		<div class="box-body box-form">
			<g:if test="${flash.message}">
				<div class="alert alert-success alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${areaAtendimentoInstance}">
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					O campo precisa ser corrigido.
				</div>
			</g:hasErrors>
			<g:form useToken="true" class="form-horizontal" novalidate="novalidate" name="areaAtendimentoInstanceForm" url="[resource:areaAtendimentoInstance, action:'save']" >
			<g:render template="form"/>
			</g:form>
		</div>
		<div class="box-footer clearfix">
			<button type="submit" form="areaAtendimentoInstanceForm" class="btn btn-success pull-right"><i class="fa fa-check"></i> <g:message code="default.button.create.label"  default="Create"/></button>
			<g:link action="index" class="btn btn-danger pull-left"><i class="fa fa-close"></i>Cancelar</g:link>
		</div>
		</div>
	</div>
</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("areaAtendimentoOpt");
        });
</g:javascript>
</body>
</html>

grails-app/views/areaAtendimento/edit.gsp
<%@ page import="br.edu.unirn.tickit.dominio.AreaAtendimento" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'areaAtendimento.label', default: 'Área de Atendimento')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<!-- Content Header (Page header) -->
<section class="content-header">
	<ol class="breadcrumb">
		<li><g:link class="list" action="index">Listagem</g:link></li>
		<li class="active"><g:message code="default.edit.label" args="[entityName]" /></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<!-- Default box -->
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.edit.label" args="[entityName]" /></h3>
			<div class="box-tools pull-right">
				<g:link class="btn btn-default btn-box-tool" action="create"><i class="fa fa-plus"></i> <g:message code="default.new.label" args="[entityName]" /></g:link>
			</div>
		</div>
		<div class="box-body box-form">
			<g:if test="${flash.error}">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					${flash.error}
				</div>
			</g:if>
			<g:if test="${flash.message}">
				<div class="alert alert-success alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${equipamentoInstance}">
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					O campo precisa ser corrigido.
				</div>
			</g:hasErrors>
			<g:form useToken="true" class="form-horizontal" novalidate="novalidate" name="areaAtendimentoInstanceForm" url="[resource:areaAtendimentoInstance, action:'update']" method="PUT" >
			<g:hiddenField name="version" value="${areaAtendimentoInstance?.version}" />
			<g:render template="form"/>
			</g:form>
		</div>
		<div class="box-footer clearfix">
			<button type="submit" form="areaAtendimentoInstanceForm" class="btn btn-success pull-right"><i class="fa fa-check"></i> <g:message code="default.button.update.label"  default="Update"/></button>

			<g:link action="index" class="btn btn-danger pull-left"><i class="fa fa-close"></i>Cancelar</g:link>
		</div>
		</div>
	</div>
</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("areaAtendimentoOpt");
        });
</g:javascript>
</body>
</html>

grails-app/views/areaAtendimento/index.gsp
<%@ page import="br.edu.unirn.tickit.dominio.AreaAtendimento" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="administrativo">
		<g:set var="entityName" value="${message(code: 'areaAtendimento.label', default: 'AreaAtendimento')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>


	<!-- Content Header (Page header) -->
	<section class="content-header">
		<ol class="breadcrumb">
			<li class="active">Listagem</li>
		</ol>
	</section>





	<!-- Main content -->
<section class="content">
	<!-- Default box -->
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title">Lista de Áreas de atendimento (${areaAtendimentoInstanceCount})</h3>
			<div class="box-tools pull-right">
				<g:link class="btn btn-default btn-box-tool" action="create"><i class="fa fa-plus"></i> Nova área de atendimento</g:link>
			</div>
		</div>
		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					<g:form action="index">
						<a href="#pesquisa" data-toggle="collapse" class="pull-right help-block collapse-btn">Pesquisar</a>
						<div class="col-xs-12 margin-bottom-10 collapse" id="pesquisa">
							<div class="row">
								<div class="col-sm-5">
									<div class="form-group">
										<label class="control-label" for="nome">Nome</label>
										<g:textField name="nome" class="form-control input-sm" value="${params?.nome}"/>
									</div>
								</div>


								<div class="col-sm-2 padding-top-20">
									<button type="submit" class="btn btn-block btn-primary"><i class="fa fa-search"></i>Pesquisar</button>
								</div>
							</div>
						</div>
					</g:form>
				</div>
				<div class="col-xs-12">
					<g:if test="${flash.message}">
						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
							<div class="message" role="status">${flash.message}</div>
						</div>
					</g:if>
					<table class="table table-bordered table-condensed">
						<thead>
						<tr>
							
							<g:sortableColumn params="[q: "${query?:''}"]" property="nome" title="${message(code: 'areaAtendimento.nome.label', default: 'Nome')}" />
							
							


							<th width="9%" colspan="3">&nbsp;</th>
						</tr>
						</thead>
						<tbody>
						<g:each in="${areaAtendimentoInstanceList}" status="i" var="areaAtendimentoInstance">
							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
								
								
								<td>${fieldValue(bean: areaAtendimentoInstance, field: "nome")}</td>
								
								
								

								<td class="text-center">
									<g:link class="btn btn-xs btn-default" action="show" id="${areaAtendimentoInstance.id}" data-toggle="tooltip" data-placement="bottom" title="Visualizar"><i class="fa fa-eye"></i></g:link>
									<g:link class="btn btn-xs btn-default" action="edit" id="${areaAtendimentoInstance.id}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="fa fa-pencil"></i></g:link>
									<g:form useToken="true" url="[resource:areaAtendimentoInstance, action:'delete']" method="DELETE" style="display: inline-block;">
										<button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="bottom" title="Remover" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"><i class="glyphicon glyphicon-remove"></i></button>
									</g:form>
								</td>
							</tr>
						</g:each>
						</tbody>
					</table>
					<div class="pagination">
						<g:paginate params="[q: "${query?:''}"]" class="pagination-sm" total="${areaAtendimentoInstanceCount ?: 0}" />
					</div>
				</div>
			</div>
		</div><!-- /.box-body -->
	</div><!-- /.box -->

</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("areaAtendimentoOpt");
        });
</g:javascript>
	
	</body>
</html>

grails-app/views/areaAtendimento/show.gsp
<%@ page import="br.edu.unirn.tickit.dominio.AreaAtendimento" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'areaAtendimento.label', default: 'Área de Atendimento')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<section class="content-header">
	<ol class="breadcrumb">
		<li class="active">Listagem</li>
		<li class="active"><g:message code="default.show.label" args="[entityName]" /></li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.show.label" args="[entityName]" /></h3>
		</div>

		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					<table class="table table-view table-condensed">
						<thead>
							<tr>
								<th colspan="2">
									Dados da ${entityName}
								</th>
							</tr>
						</thead>
						<tbody>
							
							<g:if test="${areaAtendimentoInstance?.nome}">
								<tr>
									<td><strong><g:message code="areaAtendimento.nome.label" default="Nome" />:</strong></td>
									
									<td><g:fieldValue bean="${areaAtendimentoInstance}" field="nome"/></td>
									
								</tr>
							</g:if>

							<g:if test="${areaAtendimentoInstance?.email}">
								<tr>
									<td><strong><g:message code="areaAtendimento.email.label" default="Email" />:</strong></td>
									
									<td><g:fieldValue bean="${areaAtendimentoInstance}" field="email"/></td>
									
								</tr>
							</g:if>
							
							<g:if test="${areaAtendimentoInstance?.ativo}">
								<tr>
									<td><strong><g:message code="areaAtendimento.ativo.label" default="Ativo" />:</strong></td>
									
									<td><g:formatBoolean boolean="${areaAtendimentoInstance?.ativo}" /></td>
									
								</tr>
							</g:if>
							
							<g:if test="${areaAtendimentoInstance?.dateCreated}">
								<tr>
									<td><strong><g:message code="areaAtendimento.dateCreated.label" default="Data de Cadastro" />:</strong></td>
									
									<td><g:formatDate date="${areaAtendimentoInstance?.dateCreated}" format="dd/MM/yyyy HH:mm"/></td>
									
								</tr>
							</g:if>
							
							<g:if test="${areaAtendimentoInstance?.usuarioCadastrante}">
								<tr>
									<td><strong><g:message code="areaAtendimento.usuarioCadastrante.label" default="Usuário Cadastrante" />:</strong></td>
									
									<td><g:link controller="usuario" action="show" id="${areaAtendimentoInstance?.usuarioCadastrante?.id}">${areaAtendimentoInstance?.usuarioCadastrante?.encodeAsHTML()}</g:link></td>
									
								</tr>
							</g:if>
							
						</tbody>
					</table>
					<div class="box-footer clearfix">
						<g:link action="index" class="btn btn-primary pull-right"><i class="fa fa-reply"></i>Voltar</g:link>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("areaAtendimentoOpt");
        });
</g:javascript>
</body>
</html>