grails-app/domain/br/edu/unirn/tickit/dominio/Instituicao.groovy
package br.edu.unirn.tickit.dominio

import br.edu.unirn.tickit.acesso.Usuario
/**
 * Classe responsável por Armazenar informações sobre Instituição.
 * @author: Jefferson Silva
 */
class Instituicao {

    String nome
    boolean ativo = Boolean.TRUE
    Usuario usuarioCadastrante
    Date dateCreated

    @Override
    String toString() {
        nome
    }

    static constraints = {
        nome unique: true, blank:false
        ativo(attributes:[showInForm:false])
        dateCreated(attributes:[fieldName: "Data de Cadastro"])
    }

    static mapping = {
        dateCreated column: "data_de_cadastro"
    }

    static searchFields = ["nome"]
}

grails-app/controllers/br/edu/unirn/tickit/dominio/InstituicaoController.groovy
package br.edu.unirn.tickit.dominio


import org.codehaus.groovy.grails.commons.GrailsClassUtils
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class InstituicaoController {

    static scaffold = true

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        def instituicaoInstance = new Instituicao()
        def criteriaResult = Instituicao.createCriteria().list(params) {
            if(instituicaoInstance.properties.containsKey('ativo'))
                eq("ativo",Boolean.TRUE)

            if (params.q) {
                or {
                    GrailsClassUtils?.getStaticPropertyValue(Instituicao, "searchFields")?.each {
                        def property = GrailsClassUtils?.getPropertyType(Instituicao, it)
                        if (property && Number.isAssignableFrom(property) || (property?.isPrimitive() && property != boolean)) {
                            if (property == Integer)
                                eq(it, params.int("q"))
                        } else if (property == String) {
                            ilike(it, params.q + "%")
                        }
                    }
                }
            }
        }
        respond criteriaResult, model:[instituicaoInstanceCount: criteriaResult.totalCount, params:params]
    }

    @Transactional
    def save(Instituicao instituicaoInstance) {
        withForm{
            if (instituicaoInstance == null) {
                notFound()
                return
            }

            instituicaoInstance.usuarioCadastrante = session?.usuario

            instituicaoInstance.clearErrors()
            instituicaoInstance.save(flush: true)

            if (instituicaoInstance.hasErrors()) {
                respond instituicaoInstance.errors, view:'create'
                return
            }

            instituicaoInstance.save flush:true

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.created.message', args: [message(code: 'instituicao.label', default: 'Instituição'),instituicaoInstance], encodeAs: "None")
                    redirect action: "index", method: "GET"
                }
                '*' { respond instituicaoInstance, [status: CREATED] }
            }
        }.invalidToken{
            flash.message = "Requisição inválida. Por favor, tente reiniciar a operação"
            redirect action: 'index'
        }
    }

    @Transactional
    def update(Instituicao instituicaoInstance) {
        withForm{
            if (instituicaoInstance == null) {
                notFound()
                return
            }

            if (instituicaoInstance.hasErrors()) {
                respond instituicaoInstance.errors, view:'edit'
                return
            }

            instituicaoInstance.save flush:true

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'Instituicao.label', default: 'Instituição'),instituicaoInstance], encodeAs: "None")
                    redirect action: "index", method: "GET"
                }
                '*'{ respond instituicaoInstance, [status: OK] }
            }
        }.invalidToken{
            flash.message = "Requisição inválida. Por favor, tente reiniciar a operação"
            redirect action: 'index'
        }
    }

    @Transactional
    def delete(Instituicao instituicaoInstance) {
        withForm{
            if (instituicaoInstance == null) {
                notFound()
                return
            }

            if(instituicaoInstance.properties.containsKey("ativo")){
                instituicaoInstance.ativo = false
                instituicaoInstance.save flush:true
            }else{
                instituicaoInstance.delete flush:true
            }

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'Instituicao.label', default: 'Instituição'),instituicaoInstance], encodeAs: "None")
                    redirect action:"index", method:"GET"
                }
                '*'{ render status: NO_CONTENT }
            }
        }.invalidToken{
            flash.message = "Requisição inválida. Por favor, tente reiniciar a operação"
            redirect action: 'index'
        }
    }
}

grails-app/views/instituicao/_form.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Instituicao" %>



<div class="form-group ${hasErrors(bean: instituicaoInstance, field: 'nome', 'error')} required">
	<label for="nome" class="col-sm-2 control-label">
		<g:message code="instituicao.nome.label" default="Nome" />:
		<span class="required-indicator">*</span>
	</label>
	<div class="col-sm-5">
		<g:textField name="nome" required="" maxlength="255" value="${instituicaoInstance?.nome}"/>

		<g:hasErrors bean="${instituicaoInstance}" field="nome">
			<span class="help-block error"><g:renderErrors bean="${instituicaoInstance}" field="nome" as="list" /></span>
		</g:hasErrors>
	</div>
</div>

grails-app/views/instituicao/create.gsp
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'instituicao.label', default: 'Instituição')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<!-- Content Header (Page header) -->
<section class="content-header">
	<ol class="breadcrumb">
		<li><g:link class="list" action="index">Listagem</g:link></li>
		<li class="active"><g:message code="default.new.label" args="[entityName]" /></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<!-- Default box -->
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.create.label" args="[entityName]" /></h3>
		</div>
		<div class="box-body box-form">
			<g:if test="${flash.message}">
				<div class="alert alert-success alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${instituicaoInstance}">
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					Alguns campos precisam ser corrigidos.
				</div>
			</g:hasErrors>
			<g:form useToken="true" class="form-horizontal" novalidate="novalidate" name="instituicaoInstanceForm" url="[resource:instituicaoInstance, action:'save']" >
			<g:render template="form"/>
			</g:form>
		</div>
		<div class="box-footer clearfix">
			<button type="submit" form="instituicaoInstanceForm" class="btn btn-success pull-right"><i class="fa fa-check"></i> <g:message code="default.button.create.label"  default="Create"/></button>
			<g:link action="index" class="btn btn-danger pull-left"><i class="fa fa-close"></i>Cancelar</g:link>
		</div>
		</div>
	</div>
</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("instituicaoOpt");
        });
</g:javascript>
</body>
</html>

grails-app/views/instituicao/edit.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Instituicao" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'instituicao.label', default: 'Instituição')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<!-- Content Header (Page header) -->
<section class="content-header">
	<ol class="breadcrumb">
		<li><g:link class="list" action="index">Listagem</g:link></li>
		<li class="active"><g:message code="default.edit.label" args="[entityName]" /></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<!-- Default box -->
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.edit.label" args="[entityName]" /></h3>
			<div class="box-tools pull-right">
				<g:link class="btn btn-default btn-box-tool" action="create"><i class="fa fa-plus"></i> <g:message code="default.new.label" args="[entityName]" /></g:link>
			</div>
		</div>
		<div class="box-body box-form">
			<g:if test="${flash.error}">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					${flash.error}
				</div>
			</g:if>
			<g:if test="${flash.message}">
				<div class="alert alert-success alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${instituicaoInstance}">
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					Alguns campos precisam ser corrigidos.
				</div>
			</g:hasErrors>
			<g:form useToken="true" class="form-horizontal" novalidate="novalidate" name="instituicaoInstanceForm" url="[resource:instituicaoInstance, action:'update']" method="PUT" >
			<g:hiddenField name="version" value="${instituicaoInstance?.version}" />
			<g:render template="form"/>
			</g:form>
		</div>
		<div class="box-footer clearfix">
			<button type="submit" form="instituicaoInstanceForm" class="btn btn-success pull-right"><i class="fa fa-check"></i> <g:message code="default.button.update.label"  default="Update"/></button>

			<g:link action="index" class="btn btn-danger pull-left"><i class="fa fa-close"></i>Cancelar</g:link>
		</div>
		</div>
	</div>
</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("instituicaoOpt");
        });
</g:javascript>
</body>
</html>

grails-app/views/instituicao/index.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Instituicao" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'instituicao.label', default: 'Instituição')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<!-- Content Header (Page header) -->
<section class="content-header">
	<ol class="breadcrumb">
		<li class="active">Listagem</li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<!-- Default box -->
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.list.label" args="[entityName]" /></h3>
			<div class="box-tools pull-right">
				<g:link class="btn btn-default btn-box-tool" action="create"><i class="fa fa-plus"></i> <g:message code="default.new.label" args="[entityName]" /></g:link>
			</div>
		</div>
		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					<g:form action="index">
						<div class="input-group margin-bottom-10">
							<g:textField name="q" class="form-control input-sm  pull-right" placeholder="Pesquisar" style="width: 150px;" value="${query}"/>
							<div class="input-group-btn">
								<button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
							</div>
						</div>
					</g:form>
				</div>
				<div class="col-xs-12">
					<g:if test="${flash.message}">
						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
							<div class="message" role="status">${flash.message}</div>
						</div>
					</g:if>
					<table class="table table-bordered table-condensed">
						<thead>
						<tr>
							
							<g:sortableColumn params="[q: "${query?:''}"]" property="nome" title="${message(code: 'instituicao.nome.label', default: 'Nome')}" />
							


							<th width="9%" colspan="3">&nbsp;</th>
						</tr>
						</thead>
						<tbody>
						<g:each in="${instituicaoInstanceList}" status="i" var="instituicaoInstance">
							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
								
								
								<td>${fieldValue(bean: instituicaoInstance, field: "nome")}</td>
								

								<td class="text-center">
									<g:link class="btn btn-xs btn-default" action="show" id="${instituicaoInstance.id}" data-toggle="tooltip" data-placement="bottom" title="Visualizar"><i class="fa fa-eye"></i></g:link>
									<g:link class="btn btn-xs btn-default" action="edit" id="${instituicaoInstance.id}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="fa fa-pencil"></i></g:link>
									<g:form useToken="true" url="[resource:instituicaoInstance, action:'delete']" method="DELETE" style="display: inline-block;">
										<button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="bottom" title="Remover" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"><i class="glyphicon glyphicon-remove"></i></button>
									</g:form>
								</td>
							</tr>
						</g:each>
						</tbody>
					</table>
					<div class="pagination">
						<g:paginate params="[q: "${query?:''}"]" class="pagination-sm" total="${instituicaoInstanceCount ?: 0}" />
					</div>
				</div>
			</div>
		</div><!-- /.box-body -->
	</div><!-- /.box -->

</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("instituicaoOpt");
        });
</g:javascript>
</body>
</html>

grails-app/views/instituicao/show.gsp
<%@ page import="br.edu.unirn.tickit.dominio.Instituicao" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="administrativo">
	<g:set var="entityName" value="${message(code: 'instituicao.label', default: 'Instituição')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<section class="content-header">
	<ol class="breadcrumb">
		<li class="active">Listagem</li>
		<li class="active"><g:message code="default.show.label" args="[entityName]" /></li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title"><g:message code="default.show.label" args="[entityName]" /></h3>
		</div>

		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					<table class="table table-view table-condensed">
						<thead>
							<tr>
								<th colspan="2">
									Dados do ${entityName}
								</th>
							</tr>
						</thead>
						<tbody>
							
							<g:if test="${instituicaoInstance?.nome}">
								<tr>
									<td><strong><g:message code="instituicao.nome.label" default="Nome" />:</strong></td>
									
									<td><g:fieldValue bean="${instituicaoInstance}" field="nome"/></td>
									
								</tr>
							</g:if>
							
							<g:if test="${instituicaoInstance?.ativo}">
								<tr>
									<td><strong><g:message code="instituicao.ativo.label" default="Ativo" />:</strong></td>
									
									<td><g:formatBoolean boolean="${instituicaoInstance?.ativo}" /></td>
									
								</tr>
							</g:if>
							
							<g:if test="${instituicaoInstance?.dateCreated}">
								<tr>
									<td><strong><g:message code="instituicao.dateCreated.label" default="Data de Cadastro" />:</strong></td>
									
									<td><g:formatDate date="${instituicaoInstance?.dateCreated}" format="dd/MM/yyyy HH:mm"/></td>
									
								</tr>
							</g:if>
							
							<g:if test="${instituicaoInstance?.usuarioCadastrante}">
								<tr>
									<td><strong><g:message code="instituicao.usuarioCadastrante.label" default="Usuário Cadastrante" />:</strong></td>
									
									<td><g:link controller="usuario" action="show" id="${instituicaoInstance?.usuarioCadastrante?.id}">${instituicaoInstance?.usuarioCadastrante?.encodeAsHTML()}</g:link></td>
									
								</tr>
							</g:if>
							
						</tbody>
					</table>
					<div class="box-footer clearfix">
						<g:link action="index" class="btn btn-primary pull-right"><i class="fa fa-reply"></i>Voltar</g:link>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<g:javascript>
        $(document).ready(function(){
            TICKIT.selectMenu("instituicaoOpt");
        });
</g:javascript>
</body>
</html>